name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml